# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Load the csv exported in Part I to a DataFrame

weather_csv_file = "../WeatherPy/output_data/cities.csv"

weather_df = pd.read_csv(weather_csv_file)

weather_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
0,chokurdakh,1.0,RU,1.592843e+09,65.0,70.63,147.92,43.02,13.13
1,saint george,1.0,US,1.592843e+09,14.0,37.10,-113.58,87.01,5.82
2,tumpat,40.0,MY,1.592843e+09,94.0,6.20,102.17,77.00,2.24
3,hobart,90.0,AU,1.592843e+09,93.0,-42.88,147.33,55.99,6.93
4,byron bay,0.0,AU,1.592843e+09,66.0,-28.65,153.62,52.00,6.93
...,...,...,...,...,...,...,...,...,...
541,whitehorse,75.0,CA,1.592843e+09,53.0,60.72,-135.05,50.00,6.93
542,ixtapa,5.0,MX,1.592843e+09,58.0,20.70,-105.20,87.80,3.09
543,anadyr,98.0,RU,1.592843e+09,82.0,64.75,177.48,60.80,4.47
544,banda aceh,100.0,ID,1.592843e+09,81.0,5.56,95.32,79.25,17.00
545,itarema,0.0,BR,1.592843e+09,60.0,-2.92,-39.92,85.35,11.16

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key

gmaps.configure(api_key=g_key)

In [4]:
# Convert Humidity to float and store

weather_df = weather_df.dropna()

humidity = weather_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations

locations = weather_df[["Latitude", "Longitude"]].astype(float)

weather_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
0,chokurdakh,1.0,RU,1.592843e+09,65.0,70.63,147.92,43.02,13.13
1,saint george,1.0,US,1.592843e+09,14.0,37.10,-113.58,87.01,5.82
2,tumpat,40.0,MY,1.592843e+09,94.0,6.20,102.17,77.00,2.24
3,hobart,90.0,AU,1.592843e+09,93.0,-42.88,147.33,55.99,6.93
4,byron bay,0.0,AU,1.592843e+09,66.0,-28.65,153.62,52.00,6.93
...,...,...,...,...,...,...,...,...,...
541,whitehorse,75.0,CA,1.592843e+09,53.0,60.72,-135.05,50.00,6.93
542,ixtapa,5.0,MX,1.592843e+09,58.0,20.70,-105.20,87.80,3.09
543,anadyr,98.0,RU,1.592843e+09,82.0,64.75,177.48,60.80,4.47
544,banda aceh,100.0,ID,1.592843e+09,81.0,5.56,95.32,79.25,17.00
545,itarema,0.0,BR,1.592843e+09,60.0,-2.92,-39.92,85.35,11.16

In [5]:
# Create a humidity Heatmap layer

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(weather_df["Humidity"]),
                                 point_radius = 4)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.

# Narrow down the DataFrame to find your ideal weather condition.
ideal_weather_df = weather_df


# A max temperature lower than 80 degrees but higher than 70.
ideal_weather_df = ideal_weather_df.loc[(ideal_weather_df["Max Temp"] < 80) & (ideal_weather_df["Max Temp"] > 70)]

# Wind speed less than 10 mph.
ideal_weather_df = ideal_weather_df.loc[ideal_weather_df["Wind Speed"] < 10]

# Zero cloudiness.
ideal_weather_df = ideal_weather_df.loc[ideal_weather_df["Cloudiness"] == 0]

# Drop any rows with null values
ideal_weather_df = ideal_weather_df.dropna()

ideal_weather_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
12,castro,0.0,BR,1.592843e+09,43.0,-24.79,-50.01,73.90,3.02
203,urumqi,0.0,CN,1.592843e+09,28.0,43.80,87.60,71.60,4.47
218,erzin,0.0,TR,1.592843e+09,81.0,36.96,36.20,75.99,5.99
221,paraguacu,0.0,BR,1.592843e+09,47.0,-21.55,-45.74,76.50,2.46
234,kobayashi,0.0,JP,1.592843e+09,83.0,31.98,130.98,71.01,4.00
249,longwy,0.0,FR,1.592843e+09,55.0,49.52,5.77,73.99,5.99
303,zheleznodorozhnyy,0.0,RU,1.592843e+09,43.0,55.75,38.00,71.60,2.24
350,premia de mar,0.0,ES,1.592843e+09,83.0,41.49,2.37,78.01,4.00
404,ploemeur,0.0,FR,1.592843e+09,52.0,47.73,-3.43,71.01,4.70
419,chapeco,0.0,BR,1.592843e+09,44.0,-27.10,-52.62,78.80,6.93
435,khorramabad,0.0,IR,1.592843e+09,20.0,33.49,48.36,78.48,4.23
481,hami,0.0,CN,1.592843e+09,17.0,42.80,93.45,78.62,8.03
488,grass valley,0.0,US,1.592843e+09,53.0,39.22,-121.06,79.00,2.89
502,porto belo,0.0,BR,1.592843e+09,73.0,-27.16,-48.55,79.00,6.93

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = ideal_weather_df
hotel_df["Hotel Name"] = ""
hotel_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
12,castro,0.0,BR,1.592843e+09,43.0,-24.79,-50.01,73.90,3.02,
203,urumqi,0.0,CN,1.592843e+09,28.0,43.80,87.60,71.60,4.47,
218,erzin,0.0,TR,1.592843e+09,81.0,36.96,36.20,75.99,5.99,
221,paraguacu,0.0,BR,1.592843e+09,47.0,-21.55,-45.74,76.50,2.46,
234,kobayashi,0.0,JP,1.592843e+09,83.0,31.98,130.98,71.01,4.00,
249,longwy,0.0,FR,1.592843e+09,55.0,49.52,5.77,73.99,5.99,
303,zheleznodorozhnyy,0.0,RU,1.592843e+09,43.0,55.75,38.00,71.60,2.24,
350,premia de mar,0.0,ES,1.592843e+09,83.0,41.49,2.37,78.01,4.00,
404,ploemeur,0.0,FR,1.592843e+09,52.0,47.73,-3.43,71.01,4.70,
419,chapeco,0.0,BR,1.592843e+09,44.0,-27.10,-52.62,78.80,6.93,
435,khorramabad,0.0,IR,1.592843e+09,20.0,33.49,48.36,78.48,4.23,
481,hami,0.0,CN,1.592843e+09,17.0,42.80,93.45,78.62,8.03,
488,grass valley,0.0,US,1.592843e+09,53.0,39.22,-121.06,79.00,2.89,
502,porto belo,0.0,BR,1.592843e+09,73.0,-27.16,-48.55,79.00,6.93,

In [8]:
# Base URL

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Iterrows to iterate through the dataframe

for index, row in hotel_df.iterrows():

    # Assemble url and make API request
    
    print(f"Retrieving Results for Index: {index}, hotel in {row['City']}")
    
    # Geocoordinates
    
    target_coordinates = f"{row['Latitude']}, {row['Longitude']}"
    target_search = "Hotel"
    target_radius = 50000
    target_type = "hotel"
    
    # Set up a parameters dictionary
    
    params = {
        'location': target_coordinates,
        'keyword': target_search,
        'radius': target_radius,
        'type': target_type,
        'key': g_key
        }
    
    # Pull data from API
    
    hotel_data = requests.get(base_url, params=params).json()
    
    # Extract results
    
    results = hotel_data['results']
    
    try:
        hotel_df.loc[index, 'Hotel Name'] = results[0]["name"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")


hotel_df

Retrieving Results for Index: 12, hotel in castro
Retrieving Results for Index: 203, hotel in urumqi
Retrieving Results for Index: 218, hotel in erzin
Retrieving Results for Index: 221, hotel in paraguacu
Retrieving Results for Index: 234, hotel in kobayashi
Retrieving Results for Index: 249, hotel in longwy
Retrieving Results for Index: 303, hotel in zheleznodorozhnyy
Retrieving Results for Index: 350, hotel in premia de mar
Retrieving Results for Index: 404, hotel in ploemeur
Retrieving Results for Index: 419, hotel in chapeco
Retrieving Results for Index: 435, hotel in khorramabad
Retrieving Results for Index: 481, hotel in hami
Retrieving Results for Index: 488, hotel in grass valley
Retrieving Results for Index: 502, hotel in porto belo

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
12,castro,0.0,BR,1.592843e+09,43.0,-24.79,-50.01,73.90,3.02,Premium Vila Velha Hotel
203,urumqi,0.0,CN,1.592843e+09,28.0,43.80,87.60,71.60,4.47,Hilton Urumqi
218,erzin,0.0,TR,1.592843e+09,81.0,36.96,36.20,75.99,5.99,Ramada Iskenderun
221,paraguacu,0.0,BR,1.592843e+09,47.0,-21.55,-45.74,76.50,2.46,Class Hotel Varginha
234,kobayashi,0.0,JP,1.592843e+09,83.0,31.98,130.98,71.01,4.00,Sheraton Grande Ocean Resort
249,longwy,0.0,FR,1.592843e+09,55.0,49.52,5.77,73.99,5.99,DoubleTree by Hilton Hotel Luxembourg
303,zheleznodorozhnyy,0.0,RU,1.592843e+09,43.0,55.75,38.00,71.60,2.24,Moscow Marriott Grand Hotel
350,premia de mar,0.0,ES,1.592843e+09,83.0,41.49,2.37,78.01,4.00,Hotel Barcelona 1882
404,ploemeur,0.0,FR,1.592843e+09,52.0,47.73,-3.43,71.01,4.70,HÃ´tel Mercure Quimper Centre
419,chapeco,0.0,BR,1.592843e+09,44.0,-27.10,-52.62,78.80,6.93,Pratas Thermas Resort
435,khorramabad,0.0,IR,1.592843e+09,20.0,33.49,48.36,78.48,4.23,"Hotel Atr Khorramabad , Ù‡ØªÙ„ Ø¹Ø·Ø± Ø®Ø±Ù… Ø¢Ø¨Ø§Ø¯"
481,hami,0.0,CN,1.592843e+09,17.0,42.80,93.45,78.62,8.03,Hami Rubik's Cube Hotel
488,grass valley,0.0,US,1.592843e+09,53.0,39.22,-121.06,79.00,2.89,Hyatt Place Sacramento/Roseville
502,porto belo,0.0,BR,1.592843e+09,73.0,-27.16,-48.55,79.00,6.93,Maria do Mar Hotel

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Hotel locations 

locations = hotel_df[["Latitude", "Longitude"]]

# Marker layer 

marker = gmaps.marker_layer(locations,info_box_content = hotel_info)

In [12]:
# Add marker layer ontop of heat map

marker = gmaps.marker_layer(locations,info_box_content = hotel_info)
fig.add_layer(marker)

# Display figure

fig

Figure(layout=FigureLayout(height='420px'))